#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"
require "pathname"
require "rbconfig"
require_relative "../lib/strict_yaml"

module PagesBuild
  ROOT = File.expand_path("..", __dir__)
  DEFAULT_OUTPUT = File.join(ROOT, "dist")
  OUTPUT_MARKER_SUFFIX = ".explainer-pages-output"
  LEGACY_OUTPUT_MARKER = ".explainer-pages-output"

  ROOT_ASSETS = %w[
    index.html
    landing.js
    styles.css
    theme-init.js
    theme-state.mjs
  ].freeze

  RENDERER_ASSETS = %w[
    renderer/architecture/board-surface.mjs
    renderer/architecture/comparison-board-renderer.mjs
    renderer/architecture/comparison-state.mjs
    renderer/architecture/content-grid.mjs
    renderer/architecture/deep-link-state.mjs
    renderer/architecture/edge-annotations.mjs
    renderer/architecture/flow-families.mjs
    renderer/architecture/index.html
    renderer/architecture/manifest-index.js
    renderer/architecture/math-notation.mjs
    renderer/architecture/orthogonal-routing.mjs
    renderer/architecture/question-context.mjs
    renderer/architecture/renderer-model.mjs
    renderer/architecture/renderer.js
    renderer/architecture/repeat-regions.mjs
    renderer/architecture/representation-glyphs.mjs
    renderer/architecture/semantic-pseudocode.mjs
    renderer/architecture/semantic-routing.mjs
    renderer/architecture/visual-segments.mjs
    renderer/architecture/workspace-selection.mjs
  ].freeze

  GENERATED_ASSETS = {
    "_headers" => <<~HEADERS,
      /*
        X-Content-Type-Options: nosniff
        Referrer-Policy: strict-origin-when-cross-origin
        X-Frame-Options: SAMEORIGIN
    HEADERS
  }.freeze

  class Error < StandardError; end

  module_function

  def registry
    @registry ||= StrictYaml.load_file(File.join(ROOT, "architectures/index.yaml"))
  end

  def source_set_ids
    Array(registry["source_sets"]).map { |source_set| source_set.fetch("id") }
  end

  def manifest_assets
    source_set_ids.map { |id| "renderer/architecture/manifest-#{id}.js" }
  end

  def public_files
    (ROOT_ASSETS + RENDERER_ASSETS + manifest_assets).uniq.sort
  end

  def build!(output: DEFAULT_OUTPUT, validate: true)
    output = File.expand_path(output)
    validate_output_target!(output)
    validate_sources! if validate

    stage = File.join(File.dirname(output), ".#{File.basename(output)}-stage-#{Process.pid}")
    FileUtils.rm_rf(stage)
    FileUtils.mkdir_p(stage)

    public_files.each { |path| copy_public_file(path, stage) }
    GENERATED_ASSETS.each { |path, content| write_generated_file(path, content, stage) }

    replace_output!(stage, output)
    File.write(output_marker(output), "generated by scripts/build_pages.rb\n")
    puts "Pages output: #{Pathname.new(output).relative_path_from(Pathname.new(ROOT))} (#{public_files.length + GENERATED_ASSETS.length} files)"
    output
  ensure
    FileUtils.rm_rf(stage) if stage && File.exist?(stage)
  end

  def validate_sources!
    run!(RbConfig.ruby, "renderer/architecture/build-manifest.rb")
    source_set_ids.each do |id|
      run!(RbConfig.ruby, "scripts/verify_architecture.rb", "--source-set", id)
    end
    run!(RbConfig.ruby, "renderer/architecture/build-manifest.rb", "--check")
  end

  def run!(*command)
    return if system(*command, chdir: ROOT)

    raise Error, "command failed: #{command.join(' ')}"
  end

  def validate_output_target!(output)
    root = File.expand_path(ROOT)
    raise Error, "refusing to use the repository root as Pages output" if output == root
    raise Error, "refusing to use the filesystem root as Pages output" if output == File::SEPARATOR
    raise Error, "refusing to replace a symlinked Pages output" if File.symlink?(output)
    return unless File.exist?(output)
    return if Dir.exist?(output) && Dir.empty?(output)
    return if File.file?(output_marker(output))
    return if File.file?(File.join(output, LEGACY_OUTPUT_MARKER))

    raise Error, "refusing to replace non-generated output at #{output}"
  end

  def copy_public_file(path, stage)
    source = File.join(ROOT, path)
    raise Error, "missing public asset: #{path}" unless File.file?(source)

    destination = File.join(stage, path)
    FileUtils.mkdir_p(File.dirname(destination))
    FileUtils.cp(source, destination)
  end

  def output_marker(output)
    File.join(File.dirname(output), ".#{File.basename(output)}#{OUTPUT_MARKER_SUFFIX}")
  end

  def write_generated_file(path, content, stage)
    destination = File.join(stage, path)
    FileUtils.mkdir_p(File.dirname(destination))
    File.write(destination, content)
  end

  def replace_output!(stage, output)
    FileUtils.rm_rf(output) if File.exist?(output)
    FileUtils.mv(stage, output)
  end
end

PagesBuild.build! if $PROGRAM_NAME == __FILE__
